### ISSUE TITLE
Error: Could not connect

### ISSUE THREAD

**Issue by Ebnater** [MorrisSeemann/SaveDiscord_Rich-Presence#1]
Error: Could not connect
    at Socket.onerror (/home/pi/savediscord/Custom Discord RPC/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by DreiMu** [comment]
Did you specify a Your ClientID in the indej.js?

**Comment by Ebnater** [comment]
Yes, but i guess i found the error: This page: https://github.com/djs/discord-rpc doesn't exist and npm trys to get the discord-rpc package from there

**Comment by MorrisSeemann** [comment]
If u would, u can use my ClientId if u can't create your own:  **825853950833328201**

**Comment by Ebnater** [comment]
I have my own id, but the script fails

**Comment by MorrisSeemann** [comment]
Okay... u are the only one that have this error

**Comment by Ebnater** [comment]
is it compatible with linux?

**Comment by MorrisSeemann** [comment]
du u use Linux?

**Comment by MorrisSeemann** [comment]
You need to run RichPresence on the same system as Discord!

**Comment by joseywoermann** [comment]
Additional note: It only works if you use a local installation of Discord, it won't work if you use Discord in a browser.
